config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root 'user#login'

  scope :backstage do
    resources :dashboard do
      get :index
    end

    resources :user do
      get :thankyou
      get :confirmemail

      collection do
        get :index
        get :myinformation
        get :myphoto
        get :list
        post :updatecurrentuser

        get :login
        get :logout
        post :authenticate

        get :singlecountusers
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt

  has_secure_password

  validates :fullname, :length => {minimum: 3, maximum: 130}
  validates :email, :length => {minimum: 2, maximum: 100}, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates_uniqueness_of :email
  validates :password, :length => {minimum: 6, maximum: 24}, :if => :password_changing?
  validates :password, confirmation: true, :if => :password_changing?

  # Image
  has_attached_file :photo, styles: {medium: "150x150>", thumb: "40x40>"}, default_url: "/system/photo/:style/unknown-person.gif", :processors => [:cropper]
  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/jpg', 'image/png']
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def password_changing?
    !password.nil?
  end

  def email_changing? new_email
    if email != new_email
      # Ops, e-mail changed
      generate_email_auth_key # Generate new key
      self.email_token_valid = false # Cancel access
      return true
    else
      return false
    end
  end

  def generate_email_auth_key
    self.email_token = SecureRandom.hex(50) # Generate token for e-mail validation
  end

  def self.count_activated
    User.where(:activated => true).count
  end

  def self.list_all page, per_page, search
    if page.nil? && search.nil?
      User.order(:fullname => :asc)
    else
      if search.nil?
        User.order(:fullname => :asc).paginate(:page => page, :per_page => per_page)
      else
        User.where("fullname ILIKE ? OR email ILIKE ?", "%#{search}%", "%#{search}%").order(:fullname => :asc).paginate(:page => page, :per_page => per_page)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    render layout: 'backstage', :template => 'dashboard/backstage/_pages/index'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :authorized?, only: [:index,
                                     :myphoto,
                                     :mypassword,
                                     :myinfo,
                                     :update,
                                     :updatecurrentuser,
                                     :show,
                                     :list,
                                     :singlecountusers]

  def login
    render layout: 'backstage', :template => 'user/backstage/_pages/login'
  end

  def index
    render layout: 'backstage', :template => 'user/backstage/_pages/index'
  end

  def myinformation
    @user = current_user

    render layout: 'backstage', :template => 'user/backstage/_pages/myinformation'
  end

  def logout
    disconnect
    redirect_to login_user_index_path # Back to login page
  end

  def thankyou
    @user = User.find(user_id)
    @token_url_auth = generate_email_token_url @user

    render layout: 'backstage', :template => 'user/backstage/_pages/thankyou'
  end

  def confirmemail
    @user = User.find(user_id)
    @email_confirmed = false

    if !@user.nil? && !@user.email_token.nil? && @user.email_token == tokenize
      @user.email_token_valid = true
      @user.save!
      @email_confirmed = true
    end

    render layout: 'backstage', :template => 'user/backstage/_pages/confirmemail'
  end

  def list
    @page = 6
    @search = search
    @users = User.list_all page, @page, @search

    render layout: 'backstage', :template => 'user/backstage/_pages/list'
  end

  def myphoto
    render layout: 'backstage', :template => 'user/backstage/_pages/myphoto'
  end

  def authenticate
    @authenticated = false
    @user = User.new(user_param) # Load user
    # Follow the roles, email ok, activated ok, email token ok. + password
    user_authenticated = User.where(:email => @user.email, :activated => true, :email_token_valid => true).first.try(:authenticate, @user.password) # Authenticate user with password

    if user_authenticated != false && !user_authenticated.nil? # If correct
      session[:current_user] = user_authenticated.id # Authenticate!
      @authenticated = true # go go go
    else
      session[:current_user] = nil
    end

    render json: {data: current_user, validations: nil, message: (@authenticated ? nil : 'E-mail and password are incorrect')}
  end

  def create
    @user = User.new(user_param)
    @user.generate_email_auth_key
    @user.is_an_administrator = false
    @user.email_token_valid = false

    if @user.valid?
      @user.save!
      send_email_for_email_authentication @user # Send email
    end

    render json: {data: nil, validations: @user.errors.messages, thankyouurl: user_thankyou_path(@user.id)}
  end

  def update
    render json: {data: nil}
  end

  def show
    @user = User.find(id)
  end

  def updatecurrentuser
    redirect_to_login = false
    @user = current_user

    # Check if is a e-mail changing at first
    if !user_param[:email].nil? && @user.email_changing?(user_param[:email])
      send_email_for_email_authentication @user # Send email
      disconnect
      redirect_to_login = true # Disconnect
    end

    @user.update_attributes user_param # Update attributes
    @user.photo.reprocess! if @user.cropping? # Crop image if is an upload

    # Check if is a password changing to logout
    if @user.password_changing? # Password changing?
      disconnect
      redirect_to_login = true # Disconnect
    end

    render json: {data: nil, validations: @user.errors.messages, redirect_to_login: redirect_to_login}
  end

  def user_param
    params.require(:user).permit!
  end

  def user_id
    params.require(:user_id)
  end

  def id
    params.require(:id)
  end

  def page
    if params[:page].nil?
      1
    else
      params[:page]
    end
  end

  def search
    params[:search]
  end

  def tokenize
    params.require(:tokenize)
  end

  # Singles
  def singlecountusers
    render json: {single: User.count_activated}
  end

  private
  def generate_email_token_url user
    user_confirmemail_path + "?tokenize=" + user.email_token
  end

  def send_email_for_email_authentication user
    UserMailer.email_authentication(user, generate_email_token_url(user)).deliver_now
  end

  def disconnect
    session[:current_user] = nil # Destoy user logged
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/backstage/_pages/index.slim
== render 'layouts/backstage/navbar'
h3 Dashboard
hr
br
.row
  .col-md-4
    == render 'user/backstage/_jumbotron/jumbotron_count_user'

app/views/layouts/_default/_modal.slim
.modal.fade id="modal_validation"
  .modal-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4 class="modal-title" Ops! Check your data
      .modal-body
        p We found some errors trying to validate a sent data:
        div id="modal_validation_messages"
      .modal-footer
        button type="button" class="btn btn-danger" data-dismiss="modal" Ok, got it!

.modal.fade id="modal_message"
  .modal-dialog
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4 class="modal-title"
          h4 class="modal-title" Ops! Something happened
      .modal-body
        div id="modal_validation_messages"
      .modal-footer
        button type="button" class="btn btn-primary" data-dismiss="modal" Ok, got it!

app/views/layouts/backstage.slim
html
  head
    title Gardenappe Backstage
    == stylesheet_link_tag 'backstage', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'backstage', 'data-turbolinks-track' => true
    == csrf_meta_tags
  .container
    == render '/layouts/_default/modal'
    == yield

app/views/layouts/backstage/_logo.slim
br
== image_tag 'gardenappe_logo.png', :width => 200

app/views/layouts/backstage/_navbar.slim
- if user_authenticated?
  navbar.navbar-default.navbar-fixed-top role="navigation"
    .navbar-header
      a class="navbar-brand" href="#{user_index_path}"
        == image_tag 'gardenappe_minilogo.png', :width => 20
    .container-fluid
      #bs-main-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li
            a href="#{dashboard_index_path}" Dashboard
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              |Users & Access
              span class="caret"
            ul.dropdown-menu role="menu"
              li
                a href="#{list_user_index_path}"  Manage Users
        ul.nav.navbar-nav.navbar-right
            li
              a href="#{user_index_path}"
                span class="glyphicon glyphicon-user"
                |&nbsp;#{current_user.fullname}
            li
              a href="#{logout_user_index_path}"
                span class="glyphicon glyphicon-off"
                |&nbsp;Log-out
br
br
br
br

app/views/user/backstage/_forms/_form_change_my_information.slim
== form_for :user, :url => updatecurrentuser_user_index_path, :html => {:id => 'form_user_change_my_information'} do |f|
  .form-group id="email"
    == f.label :email
    == f.text_field :email, class: 'form-control', :autofocus => true
  .form-group id="fullname"
    == f.label :fullname
    == f.text_field :fullname, class: 'form-control'

  p You can also change the password.
  .form-group id="password"
    == f.password_field :password, class: 'form-control', :placeholder => :password
  .form-group id="password_confirmation"
    == f.password_field :password_confirmation, :class => 'form-control', :placeholder => :password_confirmation
  == f.submit 'Change my information', class: 'btn btn-primary'
javascript:
  ajax_callback($('#form_user_change_my_information'), function (data) {
    if (data.redirect_to_login) {
      redirect_to('#{login_user_index_path}')
    } else {
      redirect_to('#{user_index_path}')
    }
  })

app/views/user/backstage/_forms/_form_create_user.slim
== form_for :user, :url => {:action => "create"}, :html => {:id => 'form_user_create'} do |f|
  .form-group id="email"
    == f.text_field :email, class: 'form-control', :autofocus => true, :placeholder => :email
  .form-group id="fullname"
    == f.text_field :fullname, class: 'form-control', :placeholder => :fullname
  .form-group id="password"
    == f.password_field :password, class: 'form-control', :placeholder => :password
  .form-group id="password_confirmation"
    == f.password_field :password_confirmation, :class => 'form-control', :placeholder => :password_confirmation
  == f.submit 'Create my account', class: 'btn btn-primary'
javascript:
  ajax_callback($('#form_user_create'), function(data){
    redirect_to(data.thankyouurl)
  })

app/views/user/backstage/_forms/_form_login.slim
== form_for :user, :url => authenticate_user_index_path, :html => {:id => 'form_user_authenticate'} do |f|
  .form-group
    == f.text_field :email, :class => 'form-control', :placeholder => :email
  .form-group
    == f.password_field :password, :class => 'form-control', :placeholder => :password
  .form-group
    == f.submit 'Sign-in', :class => 'btn btn-primary'

div.small Send me my e-mail confirmation again!
div.small I need help to access my account
javascript:
  ajax_callback($('#form_user_authenticate'), function (data) {
    redirect_to('#{user_index_path}')
  })

app/views/user/backstage/_forms/_form_photo.slim
== form_for :user, :url => updatecurrentuser_user_index_path, :html => {:id => 'form_user_photo', multipart: true, :target => 'process_upload'} do |f|
  .form-group
    h5 Step 1 - Select a photo
    == f.file_field :photo, :onchange => 'readURL(this);'
    == f.hidden_field :crop_w, :id => :crop_w
    == f.hidden_field :crop_h, :id => :crop_h
    == f.hidden_field :crop_x, :id => :crop_x
    == f.hidden_field :crop_y, :id => :crop_y
  form-group id="step2and3"
    h5 Step 2 - Crop your image
    .row
      .col-md-8
        img id="target" src="#" width="100%"
      .col-md-4
        div id="preview-pane" class="img-circle"
          img id="preview-pane" src="#"
        br
        .form-group
          == f.submit 'Step 3 - Save my photo', :class => 'btn btn-primary'
        .form-group
          button id="reload" class="btn btn-warning" onclick="location.reload();return false;"
            |I didn't like it!
          iframe id='process_upload' onload='upload_income()'
javascript:
  $(function () {
    $('#step2and3').hide(); // Hide other steps
  })

  function upload_income(){
    alert($('#process_upload').attr('src'))
  }

  $preview = $('#preview-pane')
  $pcnt = $('#preview-pane')
  $pimg = $('#preview-pane img')
  $target = $('#target')

  xsize = $pcnt.width()
  ysize = $pcnt.height()

  function updatePreview(c) {
    if (parseInt(c.w) > 0) {
      var rx = xsize / c.w;
      var ry = ysize / c.h;

      $crop_w = Math.round(rx * $target.outerWidth())
      $crop_h = Math.round(ry * $target.outerHeight())
      $crop_x = -Math.round(rx * c.x)
      $crop_y = -Math.round(ry * c.y)

      $('#crop_w').val($crop_w)
      $('#crop_h').val($crop_h)
      $('#crop_x').val($crop_x)
      $('#crop_y').val($crop_y)

      $pimg.css({
        width: $crop_w + 'px',
        height: $crop_h + 'px',
        marginLeft: $crop_x + 'px',
        marginTop: $crop_y + 'px'
      });
    }
  }

  $target.load(function () {
    $target.Jcrop({
      minSize: [xsize, ysize],
      onChange: updatePreview,
      onSelect: updatePreview,
      setSelect: [10, 10, 150, 150],
      aspectRatio: 1
    });

    $pimg.attr('src', $('#target').attr('src'))
  })

  function readURL(input) {
    if (input.files && input.files[0]) {
      $('#step2and3').show();

      var reader = new FileReader();
      reader.readAsDataURL(input.files[0]);

      reader.onload = function (e) {
        $target.attr('src', e.target.result);
      }
    }
  }

app/views/user/backstage/_forms/_form_update_user.slim
== form_for @user, :url => user_path, :html => {:id => 'form_update_user'} do |f|
  .well
    .form-group id="fullname"
      == f.label :fullname
      == f.text_field :fullname, class: 'form-control'
    .form-group id="email"
      == f.label :email
      == f.text_field :email, class: 'form-control', :autofocus => true
  == f.submit 'Change informations', class: 'btn btn-primary'

app/views/user/backstage/_jumbotron/_jumbotron_count_user.slim
.jumbotron
  h1 id='singleusercount'
  p active users in your database
  p
    a href='#{list_user_index_path}' class='btn btn-primary btn-lg' role='button' Manage
javascript:
  singles('#{singlecountusers_user_index_path}', function(data){
    $('#singleusercount').html(data)
  })

app/views/user/backstage/_pages/confirmemail.slim
== render 'layouts/backstage/logo'
h3 Confirm e-mail
hr
div class=(!@email_confirmed ? 'alert alert-danger' : 'alert alert-success')
  - if @email_confirmed
    p Your e-mail is confirmed! Thank you!
  - else
    p Something wrong happened, we strongly advice you to generate other code at login page.
  p You'll be redirect to login page
javascript:
  setTimeout(function () {
    window.location.href = '#{login_user_index_path}'
  }, 3000);

app/views/user/backstage/_pages/index.slim
== render 'layouts/backstage/navbar'
== render 'user/backstage/_wparts/cover_head'
br
br
.row
  .col-md-4
    == render 'user/backstage/_jumbotron/jumbotron_count_user'

app/views/user/backstage/_pages/list.slim
== render 'layouts/backstage/navbar'
h3 Manage Users
hr
.row
  .col-md-1
    button id="new_user" class='btn btn-primary btn-sm' aria-label="Left Align"
      span class='glyphicon glyphicon-plus' aria-hidden="true"
      |&nbsp;Add new
  .col-md-6
    == form_tag list_user_index_path, :method => 'get', :id => 'form_search' do
      .input-group
        span class="input-group-addon" Search
        == text_field_tag :search, params[:search], :class => "form-control input-sm", :style => "width: 250px", :placeholder => "for something..."
        |&nbsp;
        button class='btn btn-default btn-sm' aria-label="Left Align"
          span class='glyphicon glyphicon-search' aria-hidden="true"
          |&nbsp;
        |&nbsp;
        button id="clear_search" class='btn btn-default btn-sm #{"hidden" unless (@search != "" && !@search.nil?)}' aria-label="Left Align"
          span class='glyphicon glyphicon-erase' aria-hidden="true"
          |&nbsp;Clear search
br
== render 'user/backstage/_wparts/list_all_users'

javascript:
  $("#clear_search").click(function(){
    $("#clear_search").hide()
      $("#search").val("")
      $("#form_search").submit()
  })

app/views/user/backstage/_pages/login.slim
== render 'layouts/backstage/logo'
h3 Welcome to Gardenappe Backstage
hr
.row
  .col-xs-6
    h4 Request a new backstage user
    == render 'user/backstage/_forms/form_create_user'
  .col-xs-6
    h4 Access with your existing backstage account
    .well
      == render 'user/backstage/_forms/form_login'

app/views/user/backstage/_pages/myinformation.slim
== render 'layouts/backstage/navbar'
== render 'user/backstage/_wparts/cover_head'
h3 Change my information
hr
.row
  .col-xs-8
    == render 'user/backstage/_forms/form_change_my_information'
  .col-xs-4
    .well
      p Attention!
      |If you change your e-mail address we're going to send you a confirmation message again,
      |and you'll be disconnect to the website until you validate yout address again!
      br
      br
      |Also for security reasons, for changing your password you'll be disconnected and forced to log in again!

app/views/user/backstage/_pages/myphoto.slim
== render 'layouts/backstage/navbar'
== render 'user/backstage/_wparts/cover_head'
h3 Change my photo
hr
p Choose other picture and change your main photo. You can also delete the actual photo.
== render 'user/backstage/_forms/form_photo'

app/views/user/backstage/_pages/new.slim
== render 'layouts/backstage/logo'
h3 Create a new user
hr
== render 'user/_forms/form_create_user'

app/views/user/backstage/_pages/show.slim
== render 'layouts/backstage/navbar'
.row
  .col-md-2
    == image_tag current_user.photo.url(:medium), :width => 150, :height => 150, :class => 'img-circle'
  .col-md-10
    == render 'user/_forms/form_update_user'

app/views/user/backstage/_pages/thankyou.slim
== render 'layouts/backstage/logo'
h3 Thank you!
hr
p Congrats! Now you're a member.
p Check your e-mail for further informations.

- if Rails.env.development?
  .alert.alert-warning
    p Because you are at development enviroment
    a href=(@token_url_auth) click here to authenticate

app/views/user/backstage/_wparts/_cover_head.slim
.row
  .col-xs-2
    == image_tag current_user.photo.url(:medium), :width => 150, :height => 150, :class => 'img-circle'
  .col-md-10
    .container
      h3 #{current_user.fullname}
      p #{current_user.email}
      // User nav
      == render 'user/backstage/_wparts/user_nav'

app/views/user/backstage/_wparts/_list_all_users.slim
- if @users.count > 0
  table class='table'
    thead
      tr
        th width="5%"
        th width="30%" Fullname
        th width="60%" E-mail
        th width="5%" Actions
    tbody
      - @users.each do |u|
        tr
          td
            == image_tag u.photo.url(:thumb), :width => 35
          td
            h5
              == u.fullname
              |&nbsp;
              - if !u.activated
                  span class='label label-danger' style="margin-right: 3px"
                    |Inactivated
              - if !u.email_token_valid
                  span class='label label-danger' style="margin-right: 3px"
                    |E-mail not confirmed
              - if u.is_an_administrator
                  span class='label label-info' style="margin-right: 3px"
                    |Is an administrator
          td
            h5
              span class='glyphicon glyphicon-envelope' aria-hidden="true"
              |&nbsp;
              a href="mailto:#{u.email}" style="color: #000000"
                == u.email
          td align="right"
            button class='btn btn-default btn-sm' aria-label="Left Align" onclick="edit_user(#{u.id})"
              span class='glyphicon glyphicon-pencil' aria-hidden="true"
              |&nbsp;Edit
  == will_paginate @users, renderer: BootstrapPagination::Rails
- else
  .well
    | No results, try again

javascript:
  function edit_user(id){
    redirect_to('/user/' + id)
  }

app/views/user/backstage/_wparts/_user_nav.slim
ul class="nav nav-pills"
  li role="presentation" class="#{'active' if action_name == 'index'}"
    a href="#{user_index_path}" Dashboard
  li role="presentation" class="#{'active' if action_name == 'myinformation'}"
    a href="#{myinformation_user_index_path}" Change my information
  //li role="presentation" class="#{'active' if action_name == 'myphoto'}"
  //  a href="#{myphoto_user_index_path}" Change my photo

app/views/user/confirmemail.slim
h3 Confirm e-mail
hr
div class=(!@email_confirmed ? 'alert alert-danger' : 'alert alert-success')
  - if @email_confirmed
    p Your e-mail is confirmed! Thank you!
  - else
    p Something wrong happened, we strongly advice you to generate other code at login page.
  p You'll be redirect to login page
javascript:
  setTimeout(function () {
    window.location.href = '/login'
  }, 3000);

app/views/user/thankyou.slim
h3 Thank you!
hr
p Congrats! Now you're a member.
p Check your e-mail for further informations.

- if Rails.env.development?
  .alert.alert-warning
    p Because you are at development enviroment
    a href=(@token_url_auth) click here to authenticate